# Generated by Django 5.0.6 on 2024-10-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_product_new_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
