# Generated by Django 5.0.6 on 2024-10-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_total_star',
            new_name='product_rate',
        ),
    ]
