# Generated by Django 5.0.6 on 2024-11-04 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_product_total_star_products_product_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cart_invoice', models.ImageField(upload_to='')),
                ('cart_totalPrice', models.IntegerField()),
                ('cart_Date', models.CharField(max_length=50)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
