# Generated by Django 5.0.6 on 2024-11-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cart_cart_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_product_size',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
