# Generated by Django 5.0.6 on 2024-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cart_cart_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_product_total_qt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
