# Generated by Django 5.0.6 on 2024-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_cart_cart_product_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_price',
            field=models.IntegerField(default=1, null=0),
            preserve_default=False,
        ),
    ]
