# Generated by Django 5.0.6 on 2024-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cart_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.IntegerField(null=True),
        ),
    ]
