# Generated by Django 5.0.6 on 2024-11-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_cart_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_totalPrice',
            new_name='cart_product_total_price',
        ),
    ]
