# Generated by Django 5.0.6 on 2024-11-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_purchase_remove_cart_cart_invoice_cart_cart_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_search_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
