# Generated by Django 5.0.6 on 2024-11-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_products_product_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_stripe_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
