# Generated by Django 5.0.6 on 2024-11-20 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_products_product_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_invoice', models.IntegerField()),
                ('transaction_total_price', models.IntegerField()),
                ('transaction_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
