# Generated by Django 5.0.6 on 2024-11-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_transaction_delete_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_number',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_invoice',
            field=models.IntegerField(default=1),
        ),
    ]
