# Generated by Django 5.0.6 on 2024-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_transaction_transaction_total_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.CharField(default=0.0006793478260869565, max_length=50),
            preserve_default=False,
        ),
    ]
