# Generated by Django 5.0.6 on 2024-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_profilePicture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='.main/static/image'),
        ),
    ]
