# Generated by Django 5.0.6 on 2024-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_user_info_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_current_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
