# Generated by Django 5.0.6 on 2024-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_products_product_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_stripe_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
