# Generated by Django 5.0.6 on 2024-12-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_products_product_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_total_review',
            field=models.IntegerField(null=True),
        ),
    ]
