# Generated by Django 5.0.6 on 2024-12-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_product_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_star',
            name='five_start_total',
        ),
        migrations.AddField(
            model_name='product_star',
            name='five_star_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_star',
            name='four_star_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_star',
            name='one_star_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_star',
            name='three_star_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_star',
            name='two_star_total',
            field=models.IntegerField(default=0),
        ),
    ]
