# Generated by Django 5.0.6 on 2024-12-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_user_review_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_profilePicture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='./main/static/img/project_img'),
        ),
    ]
