# Generated by Django 5.0.6 on 2024-12-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_products_product_id_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_role',
            field=models.CharField(default='User', editable=False, max_length=50),
        ),
    ]
