# Generated by Django 5.0.6 on 2024-12-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_user_roles_user_info_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_role',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
