# Generated by Django 5.0.6 on 2024-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_user_info_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
